#!/bin/bash
# view a static version of a webpage in a temporary directory

# hash webpage url
HASH=$(echo "$QUTE_URL" | sha1sum | cut -d ' ' -f 1)

# set count to 1 if not set
if [ -z "$QUTE_COUNT" ]; then
	QUTE_COUNT=1
fi

# download webpage and view it
mkdir -p "/tmp/static"
yes | httrack -O "/tmp/static/$HASH" -r"$QUTE_COUNT" -F "$QUTE_USER_AGENT" \
	--disable-security-limits --max-rate=0 --connection-per-second=10 "$QUTE_URL"
qutebrowser "/tmp/static/$HASH/index.html"
